version: '3.8'
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: eliza_agent
    volumes:
      - eliza:/app/data
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: eliza_client
    environment:
      - SERVER_BASE_URL=http://agent:3000
    ports:
      # Change "5173:5173" to "5174:5173" so that the host's port 5174 is used
      # (helpful if 5173 is already in use on your machine)
      - "5174:5173"
    restart: unless-stopped

volumes:
  eliza:
